CREATE DATABASE `whatinfo` /*!40100 COLLATE 'utf8_general_ci' */;

CREATE USER 'whatinfo'@'localhost' IDENTIFIED BY 'dhktdlsvhelql!!';
GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  ON *.* TO 'whatinfo'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'whatinfo'@'10.1.1.%' IDENTIFIED BY PASSWORD '*53F8BAE21B971109A1EB81EA857FD46402AD279E';
GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  ON *.* TO 'whatinfo'@'10.1.1.%' WITH GRANT OPTION;
FLUSH PRIVILEGES;